from __future__ import annotations

import json
from collections import Counter
from pathlib import Path
from typing import Any

from pydantic import BaseModel, Field

from smadw.application.judge import schedule_next_task
from smadw.domain.models import CaseState
from smadw.infrastructure.store import JsonlEventStore, ProjectionEngine


class CaseMetrics(BaseModel):
    case_id: str
    status: str
    event_count: int
    jsonl_bytes: int
    event_type_histogram: dict[str, int] = Field(default_factory=dict)
    unknowns: int
    hypotheses: int
    experiments: int
    evidence: int
    interpretations: int
    max_task_projection_bytes: int = 0
    scheduling_cycles: int = 0
    stall_cycles: int = 0
    decision_state: dict[str, Any] = Field(default_factory=dict)


def compute_case_metrics(store: JsonlEventStore, case_id: str) -> CaseMetrics:
    engine = ProjectionEngine(store)
    state = engine.project(case_id)
    if state is None:
        raise KeyError(case_id)

    events = store.load_events(case_id)
    hist = Counter(e.event_type.value for e in events)
    path = store.events_path(case_id)
    jsonl_bytes = path.stat().st_size if path.exists() else 0

    meta_path = store.case_dir(case_id) / "scheduler_meta.json"
    if meta_path.exists():
        import json

        meta = json.loads(meta_path.read_text(encoding="utf-8"))
        for k in ("scheduling_cycles", "stall_cycles", "last_progress_revision"):
            if k in meta:
                state.decision_state[k] = meta[k]

    task = schedule_next_task(state)
    proj_bytes = len(json.dumps(task.projection, default=str).encode("utf-8"))

    return CaseMetrics(
        case_id=case_id,
        status=state.status.value,
        event_count=state.event_count,
        jsonl_bytes=jsonl_bytes,
        event_type_histogram=dict(sorted(hist.items())),
        unknowns=len(state.unknowns),
        hypotheses=len(state.hypotheses),
        experiments=len(state.experiments),
        evidence=len(state.evidence),
        interpretations=len(state.interpretations),
        max_task_projection_bytes=proj_bytes,
        scheduling_cycles=int(state.decision_state.get("scheduling_cycles", 0)),
        stall_cycles=int(state.decision_state.get("stall_cycles", 0)),
        decision_state=dict(state.decision_state),
    )


def summarize_state_for_metrics(state: CaseState) -> dict[str, Any]:
    return {
        "status": state.status.value,
        "event_count": state.event_count,
        "unknowns": len(state.unknowns),
        "hypotheses": len(state.hypotheses),
        "experiments": len(state.experiments),
        "evidence": len(state.evidence),
        "interpretations": len(state.interpretations),
        "scheduling_cycles": state.decision_state.get("scheduling_cycles", 0),
        "stall_cycles": state.decision_state.get("stall_cycles", 0),
    }


def write_phase2_report(path: Path, rows: list[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Phase 2 validation report",
        "",
        "Generated by `smadw validate`. Metrics probe architectural assumptions",
        "(projection size, Event Log growth, hypothesis flood, starvation).",
        "",
        "| Scenario | Status | Events | JSONL bytes | Hyps | Exps | Max task proj B | Stall |",
        "| --- | --- | ---: | ---: | ---: | ---: | ---: | ---: |",
    ]
    for row in rows:
        m = row["metrics"]
        lines.append(
            "| {scenario} | {status} | {events} | {bytes} | {hyps} | {exps} | {proj} | {stall} |".format(
                scenario=row["scenario"],
                status=m["status"],
                events=m["event_count"],
                bytes=m["jsonl_bytes"],
                hyps=m["hypotheses"],
                exps=m["experiments"],
                proj=m["max_task_projection_bytes"],
                stall=m["stall_cycles"],
            )
        )
    lines.extend(["", "## Scenario notes", ""])
    for row in rows:
        lines.append(f"### {row['scenario']}")
        lines.append("")
        lines.append(row.get("notes", ""))
        lines.append("")
        if row.get("ok") is False:
            lines.append(f"**FAILED expectation:** {row.get('failure', 'unknown')}")
            lines.append("")
        hist = row["metrics"].get("event_type_histogram", {})
        if hist:
            lines.append("Event types: " + ", ".join(f"{k}={v}" for k, v in hist.items()))
            lines.append("")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
